[training]
device='cpu'
batch_size = 2
start_epoch = 1
epochs = 10
logdir='logs/trial1'

[optim]
lr=1e-5
lr_backbone=1e-6
lr_drop=3 # 200
weight_decay = 1e-4

[loss]

[loss.matcher]
set_cost_bbox = 5
set_cost_giou = 2

[loss.coef]
bbox = 5
giou = 2
eos = 0.1

[dataset]
annot_file = 'graph_generation/data/train.json'
img_dir = 'graph_generation/data/train'
test_img_dir = 'hand_labeled_test'

